[package]
name = "sclang"
version = "0.0.1-dev"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
pest = "2"
pest_derive = "2"

[dev-dependencies]
criterion = "0.5.1"
expect-test = "1"
memory-stats = "1.2.0"
rustyline = "14"
serial_test = "3"

[[bench]]
name="bench-1"
harness=false
