name: Rust CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose

  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: check fmt
      run: cargo fmt --check

  release-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: try release build
      run: cargo build --release

  # XXX TODO THIS IS A TEMPORARY SOLUTION, PERMANENT SOLUTION SHOULD BE FOR AUTO COMMENTING ON PRs
  # IN A SIMILAR FASHION TO THIS GitHub action but working for `iai`, NOT for Criterion:
  # - https://github.com/marketplace/actions/criterion-compare-prs
  iai-bench-verbose:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bench:
          - iai-bench-1
          - iai-bench-2
    steps:
    - run: sudo apt install valgrind
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: ${{ matrix.bench }} - HEAD
      run: RUSTFLAGS=-Awarnings cargo bench --bench ${{ matrix.bench }} --quiet
    - name: remove target/iai to avoid possibly confusing comparison (going the wrong way)
      run: rm -rf target/iai
    - run: git checkout HEAD^
    - name: ${{ matrix.bench }} - HEAD^
      run: RUSTFLAGS=-Awarnings cargo bench --bench ${{ matrix.bench }} --quiet
    - name: remove target/iai (again) to avoid possibly confusing comparison (going the wrong way)
      run: rm -rf target/iai
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: ${{ matrix.bench }} - main - XXX TBD OBVIOUSLY USELESS FOR COMMIT ON MAIN BRANCH - XXX TODO RESOLVE THIS
      run: RUSTFLAGS=-Awarnings cargo bench --bench ${{ matrix.bench }} --quiet
