name: Rust CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose

  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: check fmt
      run: cargo fmt --check

  release-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: try release build
      run: cargo build --release

  # XXX TODO THIS IS A TEMPORARY SOLUTION, PERMANENT SOLUTION SHOULD BE FOR AUTO COMMENTING ON PRs
  # IN A SIMILAR FASHION TO THIS GitHub action but working for `iai`, NOT for Criterion:
  # - https://github.com/marketplace/actions/criterion-compare-prs
  iai-bench-verbose:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Awarnings # IGNORE WARNINGS FOR NOW to keep the output clean in the various cargo bench steps
    strategy:
      matrix:
        bench:
          - iai-bench-1
          - iai-bench-2
        baseline:
          - HEAD^
          # XXX TODO: COMPARISON to main would be useless on main branch itself - XXX TODO RESOLVE THIS
          - main
    steps:
    - run: sudo apt install valgrind
    - name: actions/checkout@v4 - ${{ matrix.baseline }}
      uses: actions/checkout@v4
      if: ${{ matrix.baseline != 'HEAD^' }}
    - name: 'actions/checkout@v4 - fetch-depth: 2 for HEAD^'
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
      if: ${{ matrix.baseline == 'HEAD^' }}
    - run: git checkout HEAD^
      if: ${{ matrix.baseline == 'HEAD^' }}
    - run: git log -1 # should show the commit for baseline
    - name: ${{ matrix.bench }} - baseline (${{ matrix.baseline }})
      run: cargo bench --bench ${{ matrix.bench }} --quiet
    - uses: actions/checkout@v4
    - run: git log -1 # should show the commit under CI testing
    - name: ${{ matrix.bench }} - should show comparison for any changes from baseline (${{ matrix.baseline }})
      run: cargo bench --bench ${{ matrix.bench }} --quiet
